import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FRG Painter App',
  description: 'Generated by FRG | IT Department',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        {/* ✅ Link to PWA manifest */}
        <link
          rel='manifest'
          href='/manifest.json'
        />

        {/* ✅ Make it mobile friendly */}
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'
        />

        {/* ✅ Set theme color */}
        <meta
          name='theme-color'
          content='#000000'
        />

        {/* ✅ Add to Home screen on Android */}
        <meta
          name='mobile-web-app-capable'
          content='yes'
        />
        <meta
          name='apple-mobile-web-app-capable'
          content='yes'
        />
        <meta
          name='apple-mobile-web-app-status-bar-style'
          content='black-translucent'
        />

        {/* ✅ Optional: Icons */}
        <link
          rel='icon'
          href='/icons/icon-192x192.png'
        />
        <link
          rel='apple-touch-icon'
          href='/icons/icon-512x512.png'
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
